### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by theetherGit** [kbrgl/svelte-french-toast#20]
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at eval (/node_modules/.pnpm/svelte-french-toast@1.0.3_svelte@3.55.0/node_modules/svelte-french-toast/components/ToastIcon.svelte:33:164)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/node_modules/.pnpm/svelte-french-toast@1.0.3_svelte@3.55.0/node_modules/svelte-french-toast/components/ToastBar.svelte:57:91)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/node_modules/.pnpm/svelte-french-toast@1.0.3_svelte@3.55.0/node_modules/svelte-french-toast/components/ToastWrapper.svelte:56:90)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/node_modules/.pnpm/svelte-french-toast@1.0.3_svelte@3.55.0/node_modules/svelte-french-toast/components/Toaster.svelte:50:101)
    at Module.each (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1842:16)
    at Toaster.svelte:24:22

**Comment by swyftycodes** [comment]
I have the same issue. it only happens sometimes and seems like it's random if it happens or not

**Comment by theetherGit** [comment]
It wasn't random for me. I can reproduce it but i have to deploy my code first to do that and it's WIP so i'll drop the link when i'm done with breaking changes in my project.

**Comment by kbrgl** [comment]
@theetherGit Are you still facing this issue?

**Comment by theetherGit** [comment]
Not right now.
