### ISSUE TITLE
Getting 404 while using Toaster

### ISSUE THREAD

**Issue by socketopp** [kbrgl/svelte-french-toast#67]
I have no idea as to why this is occuring

```
SvelteKitError: Not found: /dashboard/Toaster.svelte
    at resolve (~\node_modules\@sveltejs\kit\src\runtime\server\respond.js:522:13)
    at resolve (~\node_modules\@sveltejs\kit\src\runtime\server\respond.js:322:5)
    at resolve (~\node_modules\@sveltejs\kit\src\exports\hooks\sequence.js:115:9)
    at routing (~\src\hooks.server.ts:96:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cloudflare (~\src\hooks.server.ts:68:9)
    at async Module.respond (~\node_modules\@sveltejs\kit\src\runtime\server\respond.js:319:20)
    at async ~/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22 {
  status: 404,
  text: 'Not Found'
}
```

**Comment by ElliottStorey** [comment]
Same issue here.

**Comment by ElliottStorey** [comment]
Reinstalling the library worked for me.

**Comment by socketopp** [comment]
> Reinstalling the library worked for me.

Gonna try it as well

**Comment by kbrgl** [comment]
That's odd—would you mind sharing your Svelte version and Svelte French Toast version? Or providing a minimal repro?

**Comment by thibleroy** [comment]
Same here.

**Comment by thibleroy** [comment]
Same here. Here is my package.json

```
{
	"name": "frontend2",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"test": "npm run test:integration && npm run test:unit",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --check . && eslint .",
		"format": "prettier --write .",
		"test:integration": "playwright test",
		"test:unit": "vitest"
	},
	"devDependencies": {
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"@types/eslint": "^8.56.0",
		"@types/geojson": "^7946.0.14",
		"@types/google.maps": "^3.55.8",
		"@types/leaflet": "^1.9.12",
		"@typescript-eslint/eslint-plugin": "^7.0.0",
		"@typescript-eslint/parser": "^7.0.0",
		"eslint": "^8.56.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-svelte": "^2.35.1",
		"prettier": "^3.1.1",
		"prettier-plugin-svelte": "^3.1.2",
		"svelte": "^4.2.7",
		"svelte-check": "^3.6.0",
		"tslib": "^2.4.1",
		"typescript": "^5.4.5",
		"vite": "^5.0.3",
		"vitest": "^1.2.0"
	},
	"type": "module",
	"dependencies": {
		"@turf/turf": "^6.5.0",
		"bootstrap": "^5.3.3",
		"geotiff": "^2.1.3",
		"leaflet": "^1.9.4",
		"leaflet-lasso": "^2.2.13",
		"svelte-french-toast": "^1.2.0",
		"svelte-tags-input": "^6.0.0"
	}
}

```

**Comment by ElliottStorey** [comment]
Same version for me. I am getting the error repeatedly even after completely uninstalling and reinstalling.
